### ISSUE TITLE
PartitionManager.GetCount(bool asyncOK) never set _LocalCount when a synchronous source is used

### ISSUE THREAD

**Issue by plv** [anagram4wander/VirtualizingObservableCollection#1]
Since your las commit, Count value is alway 0 if a synchronous source is used.
I have corrected it like this :

......
        public int GetCount(bool asyncOK)
        {
            int ret = 0;

            if (!_HasGotCount)
            {
                lock (this)
                {
                    if (!IsAsync)
                    {
                        ret = this.Provider.Count;
                        _LocalCount = ret;   // line added to make the correction
                    }
                    else
                    {
                        if (!asyncOK)
                        {
.....

**Comment by anagram4wander** [comment]
Thanks so much for finding that.. The nuget is also fixed.

I guess you just made the case that it's time to put together a test suite for this now.
