### ISSUE TITLE
Refreshing when data has been updated

### ISSUE THREAD

**Issue by james-lavery** [anagram4wander/VirtualizingObservableCollection#13]
Now this may be a stupid question bearing in mind we're talking about an _ObservableCollection_...

I'm displaying records from a table with potentially 1000's of records in my database table - all working really well regarding virtualisation, paging etc.

However, other processes can cause the data in the database table to be updated. Is there a built-in mechanism for _Refreshing_ the data, rather than _Resetting_ it?

My core data layer routines (using SQLite-Net) return IEnumerables, not ObservableCollections.

**Comment by anagram4wander** [comment]
The full edit set are supported - insert, append and delete - so you don't need to reset it to update :-)

**Comment by james-lavery** [comment]
Thanks - I understand that the full CRUD set is supported by my process. However I have another thread running which can update the DB and can raise an event or send a message to notify of the update.

Is there a mechanism to refresh/reset and then navigate to the same current page/record?

Sent from my Android phone using Symantec TouchDown (www.symantec.com)

-----Original Message-----

**Comment by james-lavery** [comment]
Ah - I see that current page/location are maintained when resetting. Perfect.
